project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2/Hands-on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: Hands-on_Ex1/Hands-on_Ex1.html
          - text: In-class Exercise 2
            href: In-class_Ex2/In-class_Ex2.html
          - text: In-class Exercise 3
            href: In-class_Ex3/In-class_Ex3.html
          - text: In-class Exercise 4 (Preparing Spatial Interaction Modelling Variables)
            href: In-class_Ex4/In-class_Ex04.html
          - text: In-class Exercise 5 (Spatial Econometric Interaction Modelling)
            href: In-class_Ex4/In-class_Ex5.html
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 2
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

